GET http://localhost:8080/
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/api/user
Accept: application/json

###

GET http://localhost:8080/api/user/sdeleuze
Accept: application/json

###

GET http://localhost:8080/conf
Accept: application/json

###

GET http://localhost:8080/get?param1=ok&param2=ko
Accept: application/json
